git rm --cached Monitor/Debug/Monitor.log
git rm --cached Monitor/Debug/Monitor.pch
git rm --cached Monitor/Debug/Monitor.res
git rm --cached Monitor/Debug/Monitor.tlog/CL.command.1.tlog
git rm --cached Monitor/Debug/Monitor.tlog/CL.read.1.tlog
git rm --cached Monitor/Debug/Monitor.tlog/CL.write.1.tlog
git rm --cached Monitor/Debug/Monitor.tlog/Monitor.lastbuildstate
git rm --cached Monitor/Debug/Monitor.tlog/rc.command.1.tlog
git rm --cached Monitor/Debug/Monitor.tlog/rc.read.1.tlog
git rm --cached Monitor/Debug/Monitor.tlog/rc.write.1.tlog
git rm --cached Monitor/Debug/MonitorDlg.obj
git rm --cached Monitor/Debug/stdafx.obj
git rm --cached Monitor/Debug/vc140.idb
git rm --cached Monitor/Debug/vc140.pdb
git rm --cached Monitor/Monitor.aps
git rm --cached Monitor/Release/Monitor.Build.CppClean.log
git rm --cached Monitor/Release/Monitor.log
git rm --cached Monitor/Release/Monitor.obj
git rm --cached Monitor/Release/Monitor.pch
git rm --cached Monitor/Release/Monitor.res
git rm --cached Monitor/Release/Monitor.tlog/CL.command.1.tlog
git rm --cached Monitor/Release/Monitor.tlog/CL.read.1.tlog
git rm --cached Monitor/Release/Monitor.tlog/CL.write.1.tlog
git rm --cached Monitor/Release/Monitor.tlog/Monitor.lastbuildstate
git rm --cached Monitor/Release/Monitor.tlog/link.command.1.tlog
git rm --cached Monitor/Release/Monitor.tlog/link.read.1.tlog
git rm --cached Monitor/Release/Monitor.tlog/link.write.1.tlog
git rm --cached Monitor/Release/Monitor.tlog/rc.command.1.tlog
git rm --cached Monitor/Release/Monitor.tlog/rc.read.1.tlog
git rm --cached Monitor/Release/Monitor.tlog/rc.write.1.tlog
git rm --cached Monitor/Release/MonitorDlg.obj
git rm --cached Monitor/Release/stdafx.obj
git rm --cached Monitor/Release/vc140.pdb
